import { Task, Project } from './types';

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Write API Documentation',
    description:
      'Create clear and detailed API documentation to guide developers in using the inventory and sales metrics features effectively.',
    status: 'To Do',
    priority: 'High',
    dueDate: '29 Jul',
    assigneeName: 'Admin',
    assigneeRole: 'Designer',
    assigneeAvatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    labels: 'Deployment,Deployment,Research,Design,Development,Testing',
    subtasks: [
      {
        id: 'sub-1',
        title: 'Subtask 1',
        status: 'To Do',
        priority: 'High',
        dueDate: '12 Sep 2026',
        assigneeName: 'Admin',
        assigneeAvatar:
          'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
        taskId: 'task-1',
      },
      {
        id: 'sub-2',
        title: 'Subtask 2',
        status: 'To Do',
        priority: 'Low',
        dueDate: '15 Sep 2026',
        assigneeName: 'CN',
        assigneeAvatar:
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
        taskId: 'task-1',
      },
      {
        id: 'sub-3',
        title: 'Subtask 3',
        status: 'To Do',
        priority: 'Medium',
        dueDate: '18 Sep 2026',
        assigneeName: 'Dexter',
        assigneeAvatar:
          'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=256',
        taskId: 'task-1',
      },
    ],
    comments: [
      {
        id: 'comm-1',
        content: 'dsds',
        authorName: 'Ankit Dutta',
        authorAvatar:
          'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
        createdAt: 'just now',
        taskId: 'task-1',
      },
    ],
    activityLogs: [
      {
        id: 'act-1',
        action: 'Priority Changed',
        details: 'changed priority from No priority to Urgent',
        createdAt: 'Aug 2026',
      },
      {
        id: 'act-2',
        action: 'Update Posted',
        details: 'posted an update · Aug 2026',
        createdAt: 'Aug 2026',
      },
    ],
  },
  {
    id: 'task-2',
    title: 'Implement Search Function',
    description: 'Add live fuzzy search across all tasks with keyboard shortcuts (Cmd+F).',
    status: 'To Do',
    priority: 'Low',
    dueDate: '29 Jul',
    assigneeName: 'Admin',
    assigneeRole: 'Developer',
    assigneeAvatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    labels: 'Deployment,Deployment',
  },
  {
    id: 'task-3',
    title: 'Deploy to Production',
    description: 'Configure CI/CD deployment pipelines on Vercel/Render.',
    status: 'To Do',
    priority: 'Medium',
    dueDate: '29 Jul',
    assigneeName: 'Admin',
    assigneeRole: 'DevOps',
    assigneeAvatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    labels: 'Deployment,Deployment',
  },
  {
    id: 'task-4',
    title: 'Code Review Completed',
    description: 'Review backend NestJS controller endpoints and database schemas.',
    status: 'Doing',
    priority: 'High',
    dueDate: '29 Jul',
    assigneeName: 'Admin',
    assigneeRole: 'Lead',
    assigneeAvatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    labels: 'Deployment,Deployment',
  },
  {
    id: 'task-5',
    title: 'Design Mockups Finalized',
    description: 'Finalize Figma design components and design tokens.',
    status: 'Doing',
    priority: 'Urgent',
    dueDate: '29 Jul',
    assigneeName: 'Admin',
    assigneeRole: 'Designer',
    assigneeAvatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    labels: 'Deployment,Deployment',
  },
  {
    id: 'task-6',
    title: 'Feature Testing Passed',
    description: 'QA validation across tablet, mobile and desktop responsive views.',
    status: 'Completed',
    priority: 'High',
    dueDate: '30 Jul',
    assigneeName: 'QA Team',
    assigneeRole: 'QA',
    assigneeAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    labels: 'Testing,Passed',
  },
  {
    id: 'task-7',
    title: 'UI Design Updated',
    description: 'Updated dark and light mode color palette swatches.',
    status: 'Completed',
    priority: 'Medium',
    dueDate: '31 Jul',
    assigneeName: 'Designer',
    assigneeRole: 'Designer',
    assigneeAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=256',
    labels: 'Design,Updated',
  },
  {
    id: 'task-8',
    title: 'Security Audit Scheduled',
    description: 'Schedule annual security penetration testing and code audit.',
    status: 'Completed',
    priority: 'Urgent',
    dueDate: '01 Aug',
    assigneeName: 'Security',
    assigneeRole: 'Security Lead',
    assigneeAvatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
    labels: 'Audit,Scheduled',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Design Homepage',
    priority: 'High',
    status: 'Doing',
    lead: 'Dexter',
    dueDate: '12 Sep 2026',
    team: 'Design Team',
    labels: ['Design', 'Research'],
    reporter: 'Sarah Connor',
    description: 'Create responsive homepage wireframes and UI components.',
  },
  {
    id: 'proj-2',
    name: 'Develop Login Feature',
    priority: 'Low',
    status: 'To Do',
    lead: 'Ankit Dutta',
    dueDate: '15 Sep 2026',
    team: 'Engineering Team',
    labels: ['Development', 'Feature'],
    reporter: 'Dexter',
    description: 'Build JWT authentication and social login integration.',
  },
  {
    id: 'proj-3',
    name: 'Test Payment Gateway',
    priority: 'Medium',
    status: 'Completed',
    lead: 'Alex Morgan',
    dueDate: '18 Sep 2026',
    team: 'Engineering Team',
    labels: ['Testing', 'Bug'],
    reporter: 'Ankit Dutta',
    description: 'QA stripe and paypal checkout flow integration.',
  },
  {
    id: 'proj-4',
    name: 'Mobile App Redesign',
    priority: 'Urgent',
    status: 'Doing',
    lead: 'Sarah Connor',
    dueDate: '20 Sep 2026',
    team: 'Product Management',
    labels: ['Design', 'Deployment'],
    reporter: 'Alex Morgan',
    description: 'Overhaul React Native mobile app navigation and dark theme.',
  },
  {
    id: 'proj-5',
    name: 'Database Migration',
    priority: 'No Priority',
    status: 'On Hold',
    lead: 'Admin',
    dueDate: '25 Sep 2026',
    team: 'Engineering Team',
    labels: ['Deployment'],
    reporter: 'Admin',
    description: 'Migrate PostgreSQL database to distributed cluster.',
  },
];
